before_script:
- ./scripts/travis_prebuild.sh
language: clojure
jobs:
  include:
    - stage: test & check style
      script: ./go test
    - script: ./go check-style
    - stage: check for flakyness
      script: ./go test-clj-unit-repeat
sudo: required
group: edge
cache:
  directories:
  - $HOME/.m2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6e9d7b10030f609a46cc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
